# Creating Arrays

In [130]:
#importing numpy library
import numpy as np
np.__version__

'1.19.2'

In [131]:
#function 01 creating an array 1-D
a = np.array(["lahore","Karachi","Islamabad"])

a

array(['lahore', 'Karachi', 'Islamabad'], dtype='<U9')

In [132]:
#2-D array
a = np.array([[1,2,3],[4,5,6]], dtype = int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
#function 02 in range -2-difference b/w values 
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [134]:
#function 03 array of 6 with divided values from 0-50
c = np.linspace(0,50,6)
c

array([ 0., 10., 20., 30., 40., 50.])

In [135]:
#function 04 array with zeros -3- np. of zeros
c = np.zeros((3))
c

array([0., 0., 0.])

In [136]:
#function 05 array with ones
c = np.ones((3))
c

array([1., 1., 1.])

In [137]:
#function 06 3x3 array with all values one
c = np.full((3,3),1)
c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [138]:
#function 07 3x4 array of random floating values b/w 0-100
a = np.random.rand(3,4)*100
a

array([[54.74475839, 84.6711037 ,  6.36161997, 87.79958841],
       [42.15215797, 89.03957701, 58.0677112 , 22.13136369],
       [25.04208533, 75.43546376, 85.81043344, 62.5908497 ]])

In [139]:
#function 08 3x3 array of random int values b/w 0-50 
a = np.random.randint(50, size=(3,3))
a

array([[25, 46, 48],
       [34, 43, 30],
       [ 0, 15, 26]])

In [140]:
#function 09 4x4 diagnol array
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Functions of an array

In [141]:
#function 10 reshape
b = np.arange(1,7)
b = b.reshape((3,2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [142]:
#function 11 size of an array
arr = np.array(["lahore","Karachi","Islamabad"])
arr = arr.size
arr

3

In [143]:
#function 12 shape of an array
arr = np.array([["lahore","Karachi","Islamabad"],["Multan","Faisalabad"]], dtype = list)
arr = arr.shape
arr

(2,)

In [144]:
#function 13 dimension of an array
arr = np.array([(1,2,3),(4,5,6)])
arr = arr.ndim
arr

2

In [145]:
#function 14 data type of an array
arr = np.array([1,2,3,4,5])
arr = arr.dtype
arr

dtype('int32')

In [146]:
#function 15 converting data type of an array
arr = np.array([1,2,3,4,5])
arr = arr.astype(str)
arr

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [147]:
#function 16 taking transpose of 3x2 to 2x3 array
arr = np.array([1,2,3,4,5,6])
arr = arr.reshape((3,2))
arr = arr.T
arr

array([[1, 3, 5],
       [2, 4, 6]])

In [148]:
#function 17 resizing an array
arr = np.array([1,2,3,4,5,6])
arr = np.resize(arr, (3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [149]:
#function 18 converting 2D into 1D array
arr = np.array([(1,2,3),(4,5,6)])
arr = arr.flatten()
arr

array([1, 2, 3, 4, 5, 6])

In [150]:
#function 19 converting array to a list
arr = np.array([(1,2,3),(4,5,6)])
arr = arr.tolist()
arr

[[1, 2, 3], [4, 5, 6]]

In [151]:
#function 20 sorting an array
arr = np.array((2,1,4,3))
arr = np.sort(arr)
arr

array([1, 2, 3, 4])

In [152]:
#sorting rows of an array
arr = np.array([(3,1,4),(0,2,5)])
arr = np.sort(arr, axis= 1)
arr

array([[1, 3, 4],
       [0, 2, 5]])

In [153]:
#sorting columns of an array
arr = np.array([(3,1,4),(0,2,5)])
arr = np.sort(arr, axis= 0)
arr

array([[0, 1, 4],
       [3, 2, 5]])

# Adding/Removing Elements

In [154]:
#function 21 adding element to an array
arr = np.array(["lahore","Karachi","Islamabad"])
arr = np.append(arr,"Multan")
arr

array(['lahore', 'Karachi', 'Islamabad', 'Multan'], dtype='<U9')

In [155]:
#function 22 inserting element to an array at specific index
arr = np.array(["lahore","Karachi","Islamabad"])
arr = np.insert(arr, 2, "Multan")
arr

array(['lahore', 'Karachi', 'Multan', 'Islamabad'], dtype='<U9')

In [156]:
#function 23 deleting element from an array
arr = np.array(["lahore","Karachi","Islamabad"])
arr = np.delete(arr,1, axis= 0)
arr

array(['lahore', 'Islamabad'], dtype='<U9')

In [157]:
arr = np.array([(1,2,3),(4,5,6)])
arr = np.delete(arr, 0, axis= 1)
arr

array([[2, 3],
       [5, 6]])

# Concatenating & Splitting Arrays

In [158]:
#function 24 combining arrays
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(3,1,4),(0,2,5)])
arr  = np.concatenate((arr1,arr2), axis= 0)
arr


array([[1, 2, 3],
       [4, 5, 6],
       [3, 1, 4],
       [0, 2, 5]])

In [159]:
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(3,1,4),(0,2,5)])
arr  = np.concatenate((arr1,arr2), axis= 1)
arr


array([[1, 2, 3, 3, 1, 4],
       [4, 5, 6, 0, 2, 5]])

In [160]:
#function 25 splitting an array
arr1 = np.array([1,2,3,4,5,6])
arr = np.array_split(arr1, 3)
arr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [161]:
#function 26 splitting array at 2nd index
arr1 = np.array([1,2,3,4,5,6])
arr = np.hsplit(arr1, 2)
arr

[array([1, 2, 3]), array([4, 5, 6])]

# Selecting Elements from Arrays

In [162]:
#function 27 selecting element at specific index of an array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr = arr[3]
arr

4

In [163]:
#selecting element from an 2-D array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr = arr[0,1]
arr

2

In [164]:
#function 28 slicing elements from an array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr = arr[0:8]
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [165]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr = arr[3:]
arr

array([ 4,  5,  6,  7,  8,  9, 10])

In [166]:
#slicing elements at index 0 of an 2-D array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr = arr[:,0]
arr

array([1, 6])

In [167]:
#selecting element of specific value
arr1 = np.array(["Ali","Ahmad","Usman"])
arr2 = np.array([50,60,70])
arr = arr1[(arr2<70) & (arr2>50)]
arr

array(['Ahmad'], dtype='<U5')

In [168]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr = arr[arr<7]
arr

array([1, 2, 3, 4, 5, 6])

In [169]:
#assigning new value to specific index
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[1,0] = 2
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  7,  8,  9, 10]])

# Max & Min Function

In [170]:
#function 29 getting maximum value
arr = np.array([22,34,11,55,10])
arr = np.max(arr)
arr

55

In [171]:
#function 30 getting minimum value
arr = np.array([22,34,11,55,10])
arr = np.min(arr)
arr

10

# Mathematical Operations

In [172]:
#function 31 addition of two arrays
arr1 = np.array([1,3,5,7,9,11])
arr2 = np.copy(arr1)
arr  = np.add(arr1,arr2)
arr

array([ 2,  6, 10, 14, 18, 22])

In [173]:
#addition of specific value in array
arr1 = np.array([4,9,6,2,15,10])
arr  = np.add(arr1,3)
arr

array([ 7, 12,  9,  5, 18, 13])

In [174]:
#fuction 32 subtraction of two arrays
arr1 = np.array([4,9,6,2,15,10])
arr2 = np.array([2,4,6,8,10,12])
arr  = np.subtract(arr2,arr1)
arr

array([-2, -5,  0,  6, -5,  2])

In [175]:
#subtraction of specific value from array
arr1 = np.array([4,9,6,2,15,10])
arr  = np.subtract(arr1,2)
arr

array([ 2,  7,  4,  0, 13,  8])

In [176]:
#function 33 multiplication of two arrays
arr1 = np.array([1,3,5,7,9,11])
arr2 = np.copy(arr1)
arr  = np.multiply(arr2,arr1)
arr

array([  1,   9,  25,  49,  81, 121])

In [177]:
#function 34 division of two arrays
arr1 = np.array([2,6,12,16,30,60])
arr2 = np.array([2,4,6,8,10,12])
arr  = np.divide(arr1,arr2)
arr

array([1. , 1.5, 2. , 2. , 3. , 5. ])

In [178]:
#function 35 taking square root of each element in an array
arr = np.array([1,4,9,10,16,25])
arr = np.sqrt(arr)
arr

array([1.        , 2.        , 3.        , 3.16227766, 4.        ,
       5.        ])

In [179]:
#fuction 36 taking square of each element in an array 
arr = np.array([1,4,9,10,16,25])
arr = np.square(arr)
arr

array([  1,  16,  81, 100, 256, 625], dtype=int32)

In [200]:
#function 37 assigning power to each element in an array
arr1 = np.array([1,3,5,7,9,11])
arr2 = np.array([2,3,1,5,3,2])
arr  = np.power(arr1,arr2)
arr

array([    1,    27,     5, 16807,   729,   121], dtype=int32)

In [181]:
arr1 = np.array([1,3,5,7,9,11])
arr  = np.power(arr1,2)
arr

array([  1,   9,  25,  49,  81, 121], dtype=int32)

In [182]:
#function 38 equivalence of arrays
arr1 = np.array([1,3,5,7,9,11])
arr2 = np.array([2,2,2,2,2,2])
arr  = np.array_equal(arr1,arr2)
arr

False

In [183]:
arr1 = np.array([2,2,2,2,2,2])
arr2 = np.array([2,2,2,2,2,2])
arr  = np.array_equal(arr1,arr2)
arr

True

In [184]:
#function 39 exponent of elements in an array
arr = np.array([1,2,3,4,5])
arr = np.exp(arr)
arr

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [185]:
#function 40 sine function
arr = np.array([0,30,45,60,90])
arr = np.sin(arr)
arr

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [186]:
#function 41 cosine function
arr = np.array([0,30,45,60,90])
arr = np.cos(arr)
arr

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [187]:
#function 42 log function
arr = np.array([1,30,45,60,90])
arr = np.log(arr)
arr


array([0.        , 3.40119738, 3.80666249, 4.09434456, 4.49980967])

In [188]:
#function 43 absolute values of elements
arr = np.array([1,2.6,3.5])
arr = np.abs(arr)
arr

array([1. , 2.6, 3.5])

In [189]:
#function 44 round-of function
arr = np.array([1.3,2.7,3.5])
arr = np.round(arr)
arr

array([1., 3., 4.])

In [190]:
#function 45 round-up to the nearest int value
arr = np.array([1.3,2.7,3.5])
arr = np.ceil(arr)
arr

array([2., 3., 4.])

In [191]:
#function 46 round-down to the nearest int value
arr = np.array([1.3,2.7,3.5])
arr = np.floor(arr)
arr

array([1., 2., 3.])

# Statistical Operations

In [203]:
#function 47 sum of columns in an array 
arr = np.array([[2,6,3],[5,9,15]])
arr = arr.sum(axis=0)
arr

array([ 7, 15, 18])

In [193]:
#sum of rows in an array
arr = np.array([[2,6,3],[5,9,15]])
arr = arr.sum(axis=1)
arr

array([11, 29])

In [194]:
#function 48 mean of values
arr = np.array([[2,6,3],[5,9,15]])
arr = np.mean(arr,axis=0)
arr

array([3.5, 7.5, 9. ])

In [199]:
#function 49 median of values
arr = np.array([[2,6,3],[5,9,15]])
arr = np.median(arr,axis=1)
arr

array([3., 9.])

In [204]:
#function 50 variance of values
arr = np.array([2,6,3,5,9,15])
arr = np.var(arr)
arr

18.888888888888886

In [205]:
#function 51 standard deviation of values
arr = np.array([2,6,3,5,9,15])
arr = np.std(arr)
arr

4.346134936801765